### ISSUE TITLE
Fedora image `find: command not found`

### ISSUE THREAD

**Issue by Teraskull** [jmontleon/fedora-kiwix-server#1]
Script part that causes error:
```bash
# If error, print the content of /data
if [ $? -ne 0 ]
then
    echo "Here is the content of /data:"
    find /data -type f
fi
```

Error message:
```bash
/usr/local/bin/start.sh: find: command not found
```

Add this to Dockerfile to fix the issue:
```Dockerfile
RUN dnf install findutils
```

Running the image with:
```bash
docker run --rm --name kiwix -p 5000:80 -v /root/literature/kiwix:/data quay.io/jmontleon/fedora-kiwix-server:main wikipedia_en_all_mini_2021-11.zim
```

This image creates a new anon volume, but the `kiwix/kiwix-serve` image does not.

These are volumes created by `fedora-kiwix-server`, viewed in Portainer:
![image](https://user-images.githubusercontent.com/24798198/145236327-96b2fa02-b0cd-4416-ae68-ac0794717afb.png)

There should not be an anon volume there.

Is there any reason to have this in the `Dockerfile`?
```Dockerfile
VOLUME [/data]  <--
WORKDIR /data
```

**Comment by jmontleon** [comment]
Thank you for the report.

I don't know how I ended up with `VOLUME [/data]`. I made it match https://github.com/kiwix/kiwix-tools/blob/master/docker/server/Dockerfile#L9

I also added findutils as well.

Can you see if the new image works better for you when you have time?

**Comment by Teraskull** [comment]
Thanks a lot!

Before you made the new commit, I already tested with Fedora 36 image, and it works well, size is even a bit smaller.

![image](https://user-images.githubusercontent.com/24798198/145250524-70fc3efb-99ea-4c8d-bed6-b45ad0144b62.png)

I also completely removed the `VOLUME [/data]`, and it works fine.

Can you also update the images to `quay.io/fedora/fedora:36-x86_64` in `Dockerfile`?

**Comment by jmontleon** [comment]
Done. Quay reports about 79MB instead of 101MB (guessing compressed vs uncompressed above)
